import "./globals.css";
import localFont from "next/font/local";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const yekanBakh = localFont({
  src: [
    {
      path: "../public/fonts/YekanBakh-Light.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/YekanBakh-Regular.woff2",
      weight: "200",
      style: "normal",
    },
  ],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body className={yekanBakh.className}>{children}</body>
    </html>
  );
}
